### ISSUE TITLE
Local Search in Sherlock can be unbounded

### ISSUE THREAD

**Issue by changliuliu** [sisl/NeuralVerification.jl#122]
Sherlock takes in HPolytope input, which can be unbounded. The local search function can be unbounded. For example, if we have a function y = x with constraint x>=0, the maximum on y is infinity. Global search should be fine since it only solves a feasibility problem.

* One easy fix is to require the input set to be bounded. 
* A better fix is to explicitly check for unbounded cases.

**Comment by tomerarnon** [comment]
Let's check what happens if the optimization in local_search is unbounded. Is `neurons[1]` in that case Inf/NaN/something else? And also is this easily detectible with INFEASIBLE_OR_UNBOUNDED. We can use the `y = x` test case. For now, we can make sure Sherlock is bounded along with Planet and Duality.

**Comment by tomerarnon** [comment]
Closed by #151
