### ISSUE TITLE
Reluplex wrong behavior

### ISSUE THREAD

**Issue by AvrahamRaviv** [sisl/NeuralVerification.jl#177]
following this example:
https://github.com/sisl/NeuralVerification.jl/blob/master/examples/cars_workshop/5%20image%20classification.ipynb
replacing mnist3 by mnist1, got a counterexample, but the net actually said it's the right digit:
![image](https://user-images.githubusercontent.com/56107590/95011760-ae2db400-063b-11eb-940c-55ba0dab04d7.png)
maybe it's come from a float number since the output_scores are:
![image](https://user-images.githubusercontent.com/56107590/95011823-34e29100-063c-11eb-83c7-dc4b08481ec9.png)

**Comment by tomerarnon** [comment]
Hi @AvrahamRaviv, you rightly point out that this is due to numerical issues, since the two values (labels 8 vs 1) differ by much less than machine precision. I'm assuming you're on the master branch, which uses a comparison tolerance for reluplex. This result maintains soundness, which we prioritize over completeness when necessary, but I can look into this to ensure this is the intended result.

**Comment by AvrahamRaviv** [comment]
Thanks. Is there anyway to use reluplex with both soundness and completeness?

**Comment by tomerarnon** [comment]
Only to within the bounds of numerical tolerance. But we can investigate improving completeness in these cases where the counterexample is falsifiable, as in this case, or allowing users to relax soundness (instead of completeness) in the tolerance handling.

**Comment by AvrahamRaviv** [comment]
Thanks, ill follow.
