### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by mykelk** [sisl/NeuralVerification.jl#24]
We have code coverage statistics now! I think we want to aim for at least 85% coverage. I might suggest that @tomerarnon check for dead code (which might reveal bugs) and @clazarus add any additional tests. Just click on the coverage badge in the README and then click through to the highlighted source code.

**Comment by clazarus** [comment]
Coverage decreased with the latest change to runtests.jl. I analyzed the statistics and most algorithms had increased coverage except for Planet (which went to 0) which I mistakenly (due to a dependency issue in my local machine) not include in the latest tests. I am going to add Planet now and revise the impact on the coverage. If these tests do not suffice I will add the performance tests that run quickly to runtests.jl

**Comment by tomerarnon** [comment]
I'd say we've got decent coverage. Incorporating a large network may cover a few more bits and pieces.
