### ISSUE TITLE
Flux Models

### ISSUE THREAD

**Issue by MikeInnes** [sisl/NeuralVerification.jl#25]
This package looks cool and I wonder what it'd take to get it working with Flux models. I'm basically imagining replacing 
```julia
nnet = read_nnet("examples/networks/small_nnet.nnet")
```
with
```julia
nnet = Chain(Dense(...), ...)
```
and passing it to `Problem(nnet, input_set, output_set)` still works.

Under the hood it should be a simple case of converting Flux chains to this package's internal format, something I'm happy to help out with if there's interest.

**Comment by mykelk** [comment]
Awesome! There is definitely interest in this. I think you can bypass the `.nnet` file entirely and just populate the `Network` structure in `src/utils/network.jl`. It is super simple; just a vector of weight matrices and bias vectors along with an activation function.

**Comment by tomerarnon** [comment]
Converting from `Flux`'s representation to ours would be quite simple assuming only `Dense` layers. For function layers or user-defined layers, this can get much hairier, of course.
```julia
import NeuralVerification: Layer, ReLU

Layer(d::Dense) = Layer(d.W, d.b, d.σ)
function Network(C::Chain)
    @assert all(isa.(C.layers, Dense)) "NeuralVerification only supports Dense layers"
    Network([Layer(d) for d in C.layers])
end

# e.g.:
julia> d = Dense(ones(1,1), ones(1), ReLU());

julia> Network(Chain(d,d))
Network(Layer[Layer([1.0], [1.0], ReLU()), Layer([1.0], [1.0], ReLU())])
```
Passing along `Chain`s directly (without conversion) could also be possible actually, but is much more involved. It would be interesting if at some point we could generalize the idea of a `Layer` so that it could work with `Dense` (or any others) directly, and potentially even leverage Flux's GPU capabilities as a result...

But we're not yet ripe enough to consider that too seriously!
