### ISSUE TITLE
Defining PolytopeComplements For  Regression Problem

### ISSUE THREAD

**Issue by tclayton0594** [sisl/NeuralVerification.jl#68]
Hi, 
I am an engineer at General Motors that just joined their Next Gen Controls group. A few members of my team had attended a conference where we were introduced to your tool (very interested in using) and now I am trying to use the algorithms you guys have provided on one of our own ANNs. 

Wanted to first ask whether posting implementation problems on this page was appropriate? If not, I would to get a potential contact on the tool if possible! 

I will go ahead and post my question here as well. When using methods that require PolytopeComplements as the output set, how would you define this for a regression problem? So for example, I want to check if my ANN with a single output is outputting between a lower and upper bound. How would I turn the 2 constraints into a valid PolytopeComplement for analysis? 

Thanks

**Comment by mykelk** [comment]
Hi @tclayton0594, I'm glad you are using the tool! This is definitely the right place to post implementation questions and issues. I'll let @tomerarnon answer your question.

**Comment by tomerarnon** [comment]
Hi @tclayton0594, if your output set is simply an interval (as in, a ≤ y ≤ b), then it should not be represented as a `PolytopeComplement`. We tend to represent those kinds of sets as `Hyperrectangle`s (which can be defined with `Hyperrectangle(low = a, high = b)`). Which solver/s are you trying to use?

**Comment by tclayton0594** [comment]
Thanks for the response @tomerarnon. I was trying to get outputs for as many solvers I could and then build a report of my results. We are trying to identify ways we can use the tool to validate our ANNs. 

I was trying to use the primal optimization solvers (NSVerify, MIPVerify, ILP) as well as Reluplex, but I kept getting errors when trying to represent the output set as an interval. Would these solvers be unable to handle such an output set?

**Comment by tomerarnon** [comment]
As you point out, optimization based solvers are not well suited to work with convex output constraints (such as intervals). The reason for this has to do with how linear programs are represented and solved (linear programming underlies all of the optimization methods). Instead, the optimization methods require output constraints that are the complement to a convex set. E.g. the complement of Union(y < a, y > b) is the original a < y < b.
It is still possible to use them to solve problems with convex constraints, by solving as many verification problems as there are constraints. For example, consider the original a < y < b constraint. You can split this into two problems, first showing only that y > a, then only y < b. If both conditions hold then the original constraint holds. The reason this is possible while directly solving the original is not is because the complement of a single inequality constraint is a convex set, but the complement of the intersect of two inequality constraints is not.

**Comment by tclayton0594** [comment]
Ok makes sense. Thank you for the clarification!
