### ISSUE TITLE
Inconsistent bounds in Planet

### ISSUE THREAD

**Issue by mforets** [sisl/NeuralVerification.jl#83]
If you try run the test script for `identity_network.jl` checking the construction of hyperrectangles in the function `tighten_bounds` and showing the data in case of failure, like this,

```julia
    new_bounds = Vector{Hyperrectangle}(undef, length(neurons))
    for i in 1:length(neurons)
        try
            new_bounds[i] = Hyperrectangle(low = lower[i], high = upper[i])
        catch
            @show i
            @show lower[i]
            @show upper[i]
        end
    end
    return (OPTIMAL, new_bounds)
```
The result is
```julia
i = 1
lower[i] = [0.9]
upper[i] = [-0.9]
i = 2
lower[i] = [2.3999999999999986, 2.4000000000000004]
upper[i] = [0.6000000000000001, 0.6]

i = 3
lower[i] = [12.100000000000001, 12.100000000000001]
upper[i] = [4.8999999999999995, 4.8999999999999995]
```
Hence LazySets refuses to create an hyperrectangle given these bounds (for reference, we added this consistency check in the inner constructor in [v1.16.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.16.0)).

Would it be reasonable to discard the data for which the construction criterion doesn't hold, at the risk of returning a number `< length(neurons)` of neurons? (If not, what is the meaning of such sets anyway, an empty set?)

**Comment by tomerarnon** [comment]
Hi @mforets, thanks for opening this issue as a follow up to you pr!
@changliuliu and I have taken and look at this and it turned out that any bounds where `lower > upper` indicate the problem is infeasible. However, patching this by making `lower <= upper` a strict requirement (may have) revealed another issue that went unnoticed, so I can't yet push it as a fix. We're looking into that currently.

**Comment by mforets** [comment]
Alright, thanks for taking a look!

**Comment by mforets** [comment]
Hi, do you happen to have any updates on this issue? Here is a small one: [LazySets v1.31.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.31.0) adds an option to the hyperrectangle constructor, so `Hyperrectangle(low = lower[i], high = upper[i], check_bounds=false)` can be used to ignore the bounds check, in case you still consider this as a temporary workaround for this algorithm. This change is less intrusive than globally deactivating all the assertions.

**Comment by changliuliu** [comment]
The bug was with tighten_bounds in Planet. What tighten_bounds do is to encode the whole network using triangle relaxation, then minimize or maximize the summation over all nodes to find their bounds. This formulation of tighten_bound is problematic. 

By minimizing or maximizing the summation over all nodes, it is not guaranteed to find corresponding lower or upper bounds for all nodes. Consider a simple example. Suppose we want to find bounds for x and y that satisfies the constraint: |x|+2|y|<=1. The actual bounds for x should be [-1,1]. The actual bounds for y should be [-0.5,0.5]. However, if we use tighten_bounds, then we will solve the following two problems:
min x+y s.t. |x|+2|y|<=1 			=> x = -1, y = 0
max x+y s.t. |x|+2|y|<=1			=> x = 1, y = 0

Clearly, we cannot get the correct bounds for y.

Now we only use tighten_bounds for feasibility check. If there is no solution for tighten_bounds, then the property holds. If there is a solution, then we do SAT analysis using the original bounds computed by interval arithmetic.
