### ISSUE TITLE
Implement AI2 using zonotopes

### ISSUE THREAD

**Issue by mforets** [sisl/NeuralVerification.jl#87]
The idea is relatively straightforward. Right now Ai2 relies on two core methods, `forward_partition` and `convex_hull`.

- `forward_partition` returns a vector containing the input set "rectified" (relu-ed) with respect to the axes. For HPolytopes, this is a simple intersection with a linear constraint. (LazySets has added the lazy Rectification, which may be able to serve as a stand-in for that operation, but right now we do everything concretely.) To extend this function to zonotopes, the same intersection process would still take place, but in a zonotope-over-approximate way. (This method is a stand-in for what the paper calls "meet")

- `convex_hull` is easy to imagine for general polytopes or hyperrectangles, etc.. For zonotopes, this operation is an over-approximate union-like operation. As I recall, the original paper cites a source for the method. (This method is a stand-in for what the paper calls "join").

Originally posted by @tomerarnon in https://github.com/sisl/NeuralVerification.jl/issues/85#issuecomment-586467269

**Comment by SebastianGuadalupe** [comment]
Hello! I implemented this in a fork for my JSoC. I plan to contribute the new algorithm here soon!
Here is a link to a blog showing the implementation: 
https://nextjournal.com/sguadalupe/week-2

**Comment by mforets** [comment]
in this other blog post there are a few benchmarks: https://nextjournal.com/sguadalupe/week-3

i guess now @SebastianGuadalupe can send your contribution? not sure if the plan is to write a new algorithm or modify the existing `Ai2`? @tomerarnon do you have any comments on that?

**Comment by tomerarnon** [comment]
Yes indeed, we should be ready for it now! I had in mind initially that Ai2 could be parameterized as e.g. `Ai2{Zonotope}`, `Ai2{HPolytope}`, `Ai2{Hyperrectangle}`. Different representations would in turn call different versions of meet/join that approximate accordingly. Since this isn't currently implemented, if you'd like to submit Ai2z as a new solver, that would be alright with me @SebastianGuadalupe. The two could then eventually be consolidated. If instead you'd like to collaborate on a PR to integrate Ai2z with the existing solver, I'm open to doing that as well.
